---
title: "database"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(RSQLite)
library(DBI)
library(tidyverse)
library(datamodelr)
```

```{r}
# SQLite DB 구축/연결하기
# con <- dbConnect(SQLite(), dbname = "C:/Users/MINJI/MJ/2019-2/Data_Engineering/팀플/database/SEOUL_FESTIVAL.db")
con <- dbConnect(SQLite(), dbname = "./SEOUL_FESTIVAL.db")
```



```{r}
festival_info_1516 <- dbGetQuery(con, "SELECT * FROM FESTIVAL_INFO_1516")
festival_info <- dbGetQuery(con, "SELECT * FROM FESTIVAL_INFO")
festival_cluster <- dbGetQuery(con, "SELECT * FROM FESTIVAL_cluster")
float_pop <- dbGetQuery(con, "SELECT * FROM FLOAT_POP")

restaurant_info <- dbGetQuery(con, "SELECT * FROM RESTAURANT_INFO")
festival_restaurant <- dbGetQuery(con, "SELECT * FROM FESTIVAL_RESTAURANT")
```


```{r}
data_model <- dm_from_data_frames(festival_info, festival_cluster, float_pop, festival_info_1516, restaurant_info, festival_restaurant)

data_model <- dm_add_references(
  data_model,
  festival_info$festival_id == festival_cluster$festival_id,
  festival_info_1516$festival_no == float_pop$festival_no,
  festival_info$festival_id == festival_restaurant$festival_id,
  restaurant_info$id == festival_restaurant$restaurants_id
)

table_segments <- list(
  Analysis = c("float_pop", "festival_info_1516"),
  Distribution = c("festival_info", "restaurant_info", "festival_restaurant", "festival_cluster"))

dm_dvdrental_seg <- dm_set_segment(data_model, table_segments)

graph <- dm_create_graph(dm_dvdrental_seg, rankdir = "LR", col_attr = c("column", "type"))#, view_type = "keys_only")
dm_render_graph(graph)
dm_export_graph(graph, "db_schema_res.png", file_type = "png")
```


```{r}
dbDisconnect(con)
```

